# Generated by Django 5.2.16 on 2026-07-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(default='Monday,Tuesday,Wednesday,Thursday,Friday', max_length=100),
        ),
    ]
